  const styles = {
    heroSection: {
      minHeight: '80vh',
      padding: '40px',
      display: 'flex',
      alignItems: 'center',
      position: 'relative',
      overflow: 'hidden',
    },
    decorativeBefore: {
      position: 'absolute',
      width: '800px',
      height: '800px',
      background: 'rgba(180, 230, 240, 0.3)',
      borderRadius: '50%',
      top: '-200px',
      left: '-200px',
      zIndex: 0,
    },
    decorativeAfter: {
      position: 'absolute',
      width: '600px',
      height: '600px',
      background: 'rgba(200, 240, 200, 0.3)',
      borderRadius: '50%',
      bottom: '-150px',
      right: '-150px',
      zIndex: 0,
    },
    container: {
      maxWidth: '1400px',
      margin: '0 auto',
      padding: '0 50px',
      position: 'relative',
      zIndex: 1,
      width: '100%',
    },
    grid: {
      display: 'grid',
      gridTemplateColumns: '1fr 1fr',
      gap: '80px',
      alignItems: 'center',
    },
    content: {
      paddingRight: '40px',
    },
    subtitle: {
      color: '#999',
      fontSize: '13px',
      fontWeight: '600',
      letterSpacing: '1.5px',
      marginBottom: '25px',
      textTransform: 'uppercase',
    },
    title: {
      fontSize: '64px',
      fontWeight: '700',
      lineHeight: '1.15',
      marginBottom: '25px',
    },
    titleBlue: {
      color: '#5855ff',
    },
    titleRed: {
      color: '#ff3333',
    },
    description: {
      color: '#555',
      fontSize: '16px',
      lineHeight: '1.6',
      marginBottom: '40px',
    },
    buttonGroup: {
      display: 'flex',
      gap: '20px',
      flexWrap: 'wrap',
    },
    btnBase: {
      padding: '15px 30px',
      fontSize: '14px',
      fontWeight: '600',
      border: 'none',
      borderRadius: '6px',
      cursor: 'pointer',
      display: 'inline-flex',
      alignItems: 'center',
      gap: '10px',
      transition: 'all 0.3s ease',
      textTransform: 'uppercase',
      letterSpacing: '0.5px',
    },
    btnPrimary: {
      background: '#ff7744',
      color: 'white',
      boxShadow: '0 4px 15px rgba(255, 119, 68, 0.3)',
    },
    btnSecondary: {
      background: 'white',
      color: '#ff7744',
      border: '2px solid #ff7744',
      boxShadow: '0 4px 15px rgba(0, 0, 0, 0.1)',
    },
    illustration: {
      position: 'relative',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
    },
    illustrationImg: {
      width: '100%',
      maxWidth: '650px',
      height: 'auto',
      filter: 'drop-shadow(0 20px 40px rgba(0, 0, 0, 0.1))',
    },
    icon: {
      width: '18px',
      height: '18px',
    },
  };